### ISSUE TITLE
defile

### ISSUE THREAD

**Issue by ChloeTax** [ChloeTax/hexxytest3#45]
https://modrinth.com/mod/defile
from https://github.com/ChloeTax/hexxytest3/issues/43

**Comment by SupernovaXTS** [comment]
Rather overpowered and large amounts of grief potential

**Comment by abilliontrillionstars** [comment]
I agree, it's very cool but doesn't offer much interop with hex, and more seems to be its own standalone playstyle, which conflicts with our origins minus philosophy.

**Comment by walksanatora** [comment]
I was just told of https://modrinth.com/mod/undefile
which would remove the grief potential as you could just fwoosh out large areas of ink easily. (although I wouldn't mind painting my walls black).
I should have been more activ earlier as I would have tried to push back against origins- since I feel like the point of origins is to make you have to reconsider how you play and origins minus doesn't really have any species that make you re-think your base's design or features
